### ISSUE TITLE
Gem causes all rake tasks to exit with non-zero code which falsely indicates an error

### ISSUE THREAD

**Issue by machadolab** [logdna/ruby#2]
https://github.com/logdna/ruby/blob/830fa833fcb651fd69fc60e4efb91b94319db711/lib/logdna.rb#L201

With the above line, any rake task in my application that loads this gem will exit with an exit code of 1, making my CI system think the command failed.

Suggest removing the

```ryby
exit!
```

line and just letting the at_exit hander clean up @@client and not mess with the exit status.

**Comment by respectus** [comment]
Hi @machadolab,

Thanks for bringing this issue to our attention, I've taken a look and it does seem like this line is unnecessary. I've removed it from version 1.1.1 of the gem. Please do let me know if you experience any issues with the latest version. Do appreciate the feedback!
