### ISSUE TITLE
uninitialized constant Logdna

### ISSUE THREAD

**Issue by oleg-kiviljov** [logdna/ruby#20]
Hello, why the readme suggests to setup the logger by using:

Logdna::Ruby

while quick browsing of the library code shows that the actual namespace and logger class are: 

LogDNA::RubyLogger

**Comment by vilyapilya** [comment]
@oleg-kiviljov please use the way mentioned in the Readme file. We work hard on making our libraries easy to use.  If the instructions are not working or not quite clear, we will appreciate your feedback.
