### ISSUE TITLE
Logs are not sent to LogDNA

### ISSUE THREAD

**Issue by oleg-kiviljov** [logdna/ruby#21]
Hello, I've setup the logger for the rails based on the code I've found in gem (not readme)

config.logger = LogDNA::RubyLogger.new(myapikey, myhostname, opts)

but it does not send any logs to LogDNA, what can be the issue here?

**Comment by vilyapilya** [comment]
@oleg-kiviljov, please try to add this line to your config/environments/environment.rb file :

```
Rails.application.configure do
  config.logger = Logdna::Ruby.new(your_api_key, options)
end
```

It will send the logs. However, there are some known issues in our Ruby library. We are working on fixing them and going to release a new version (most likely next Thursday). 
Thank you for your question, please let us know if you have more.
