### ISSUE TITLE
Agent sending logs during requests

### ISSUE THREAD

**Issue by badosu** [logdna/ruby#30]
After including logdna to our application we are seeing increased response times, the agent is sending logs during the request lifecycle (taking up to 40% of the response time).

Given the rails gem is deprecated as per-notice, how does one configure this gem to avoid such an issue?

**Comment by badosu** [comment]
As of now, we removed the gem from our app until this is sorted out.

**Comment by vilyapilya** [comment]
@badosu we are sorry you are not satisfied with our Ruby library. Do you see the performance issue with out latest version? 1.4.2 ?

**Comment by badosu** [comment]
Hello @vilyapilya, here's the section from `Gemfile.lock`:

```
    logdna (1.4.2)
      concurrent-ruby (~> 1.0)
      json (~> 2.0)
      require_all (~> 1.4)
```

**Comment by vilyapilya** [comment]
@badosu  can you please give us more info on how you use our lib and what kind of issue you're seeing? Do you see that your application is slowing down when using the gem?

**Comment by badosu** [comment]
@vilyapilya Sure, we set it up like described on https://github.com/logdna/ruby#quick-setup.

The application has up to 40% time spent sending logs to logdna on some requests, we identified this via our monitoring agent.

**Comment by vilyapilya** [comment]
@badosu Last week on Thursday we released a new version where we stopped joining the gem's thread to the main one. The joining was slowing down the performance. Did you still have the issue after the update?

**Comment by badosu** [comment]
@vilyapilya We were using version `1.4.2`

**Comment by Geesu** [comment]
We upgraded from 1.3.0 to 1.4.2 and ran into this exact issue. Our requests were taking 8X longer. Every template render was associated with an HTTP request to logs.logdna.com/logs/ingest

The only related change is stopping the join, which is likely the issue.

Determined this from scoutapm:

![Screen Shot 2020-03-27 at 11 32 27 AM](https://user-images.githubusercontent.com/170654/77772532-ac48bf80-701e-11ea-9730-163ffc6eb31e.png)

**Comment by MaxHogervorst** [comment]
We got the same issue with all versions

**Comment by MaxHogervorst** [comment]
@smusali , @badosu any updates? It's been 2,5 months

**Comment by badosu** [comment]
I don't know? Ask the maintainers

**Comment by jakedipity** [comment]
@MaxHogervorst @badosu We have an internal ticket for tracking this issue. I'll continue to keep you updated as we investigate the issue.

**Comment by MaxHogervorst** [comment]
@jakedipity thanks for the swift reply, any ETA?

**Comment by jakedipity** [comment]
The issue is still unclear as the proposed fix in 1.4.2 didn't work. I have some ideas which I'll look into it this week and hopefully we can have a patch by end of this week / early next week.

If you know how to induce the issue with an easy to duplicate environment then that'll speed things up a bit.

**Comment by MaxHogervorst** [comment]
Sorry no example env, big requests seems to be most affected tho

**Comment by badosu** [comment]
In case it helps we were using Rails 5.2.4, we have no changes to the standard middleware stack so a simple scaffold project hopefully should be able to reproduce the issue.

**Comment by MaxHogervorst** [comment]
@jakedipity any updates?

**Comment by jakedipity** [comment]
@MaxHogervorst Due to some new issues, this issue has been lowered in priority. I am looking to returning to this once those have been addressed. We'll update the ticket when we do find a solution.

**Comment by marckohlbrugge** [comment]
We're running into the same problem. See the attached screenshot for an example of a background job taking twice as long due to the LogDNA requests. Regular Web requests are affected as well.

Note how in each screenshot the next query needs to wait for the LogDNA request to be completed first. It appears those requests happen in the same thread.

<img width="1311" alt="image" src="https://user-images.githubusercontent.com/93276/100016516-73d9cb00-2dd1-11eb-845f-314ea784d265.png">

**Comment by jakedipity** [comment]
We've recently released version 2.2.0 of our Kubernetes Agent. This has opened up some cycles for us to look into this problem. Thanks for the additional info @marckohlbrugge, I'm hoping to resolve this ASAP

**Comment by jakedipity** [comment]
Just noting this issue also ties in with PR #32

**Comment by MaxHogervorst** [comment]
We've stopped using logdna because of this

**Comment by hcatlin** [comment]
This is the exact problem we are also having... it's basically taking our website down. It POSTS on every. single. log. line.

**Comment by Geesu** [comment]
Use version `1.3.0 ` until they fix the problem. I don't understand how this hasn't been addressed yet.

**Comment by hcatlin** [comment]
@Geesu agreed... and I'm going to try the PR's code and see if htat helps.

**Comment by jakedipity** [comment]
The PR for this issue has just been merged. We should have a bumped version soon enough. I'll keep this open for a bit in case the issue persists, but we're confident this should solve most of the problems people have been seeing.

**Comment by hcatlin** [comment]
@jakedipity thanks! right now, we're working off of the branch for this PR! Will move to `main` branch now!
